### ISSUE TITLE
scrollbars for drawing area?

### ISSUE THREAD

**Issue by yanick** [nkh/P5-App-Asciio#1]
it's greedy of me, but I'd like to be able to have more drawing area that what my monitor offers me. Having scrollbars on the drawing window (or a possibility to move the view via keys) would be awesome.

**Comment by nkh** [comment]
@yanick Do you still want this? I can add it in the Asciio 2.0 requirements.

**Comment by yanick** [comment]
That'd be monster cool, yeah. :-)

**Comment by nkh** [comment]
https://github.com/nkh/Asciio-2.0/issues/18

**Comment by qindapao** [comment]
I implemented it in my fork branch

https://github.com/qindapao/P5-App-Asciio

**Comment by nkh** [comment]
nice work but I can't accept the patches in the form they have now.

OK for the code adding scrollbars, even though the window size is arbitrary
(it might already have been before your changes), it would be nicer in the
setup

not OK, repetition of byte_length in multiple files, also why not "use
utf8" and let length return the logical length? s/// string again and again
is not very efficient either.

not OK, "temp_lines", sorry but definitely not but it's a simple fix

not OK, asking for a mono font that's specific to your install, move it to
a config

not OK, changing the zoom shortcuts from +/-, ctl+/- would be fine. I have
no problems with user specific shortcuts as long as they are not the
default, same with font size. one way to do that would be to leave the
defaults as they are in the source and load an extra setup that's user
specific. IE: Zoom in' => ['C00-j', \&zoom, 1]

I don't see what the 'delete invalid codes' patch does; the %C hash is not
used nor is %K.

I hope you can clean it up a bit, I'd be very happy that Chinese speaking
users can use it too.

On my side I've looked a bit at the code to see how to speed up the
display. I think that the best way to do it is to cache the rendering, as
long as the object is not changed as described
in P5-App-Asciio/lib/App/Asciio/GTK/Asciio.pm:194, that would mean adding
the cache to the elements themselves. right now each element is rendered
onto the main canevas, via Asciio's PIXMAP (Asciio.pm:129 which is
allocated on each draw event), this would mean a PIXMAP per object and here
we need to be careful to share the same pixmap for copies of object or we'd
be using alot of resources (in your case where there are hundreds of
copies).


194 # draw elements
  1 for my $element (@{$self->{ELEMENTS}})
  2 ◐◌◌◌◌◌◌◌{
  3 ◐◌◌◌◌◌◌◌# do not draw elements that are outside the viewport
  4 ◐◌◌◌◌◌◌◌# do not draw unchanged elements, use a rendering cache


Let me know if you want to have a go at it; right now I'm busy with
something else and I don't have, shame on me,  a running Asciio installed
from source (GTK dependency problems), time to try it, maybe in a few days.

Cheers, Nadim.

**Comment by nkh** [comment]
Some scrollbar implementation done which will need to be revisited if necessary:

- changing zoom level doesn't make the widget larger, this means that objects at the bottom and far right may not be displayed; still this is the code that will be used as enlarging the widget to follow the zoom level consumes large amount of memory and cpu and zooming in to a larger extent is very seldom done

- when scrolling the mouse position is not update thus the user needs to click on the scrolled area to insert elements at the right place
