### ISSUE TITLE
USE_MARKUP_MODE has different effect in different places

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#106]
@qindapao not sure it's an issue but I was surprised the code is different 

compare 
https://github.com/nkh/P5-App-Asciio/blob/62cc570d8a1d96de17fc04ab05b9d733d35dfb6b/lib/App/Asciio/Cross.pm#L40-L44

with

https://github.com/nkh/P5-App-Asciio/blob/62cc570d8a1d96de17fc04ab05b9d733d35dfb6b/lib/App/Asciio/String.pm#L81

there are more places

**Comment by qindapao** [comment]
@nkh c6cc94f02e9f51dce12dd6873d5eec9da7976af1

Removed redundant comments and made a few minor changes.Now USE_MARKUP_MODE only appears in one place.

**Comment by nkh** [comment]
merged

**Comment by nkh** [comment]
merged

**Comment by qindapao** [comment]
@nkh Sorry, the merge was wrong, I just re-created a branch, this is it

a7b8e10dc4039ae866df749cee912fc5db835618

**Comment by nkh** [comment]
Ok, take a breath and we merge tomorrow when you are really sure.

the last commit I made is 4da67aff965304641eeed729bdf04316d9cc685a on Sep 3, 2023

rebase all you changes on that commit and squash them so there's only one commit

then send me a link to you branch, not just a a sha1 which doesn't help as it takes multiple steps for me.

in the meantime I'll rewind my repo to 4dq67...

**Comment by qindapao** [comment]
@nkh Ok, it's late at night. I'm going to sleep. I'll do it as you say tomorrow.

**Comment by qindapao** [comment]
@nkh hi, I am ready,Below is the link to the branch

https://github.com/qindapao/P5-App-Asciio/tree/other_fix

**Comment by nkh** [comment]
@qindapao merged
