### ISSUE TITLE
Document content writing progress

### ISSUE THREAD

**Issue by qindapao** [nkh/P5-App-Asciio#111]
I open this issue to track the progress of the document.

**Comment by qindapao** [comment]
@nkh 

https://github.com/qindapao/P5-App-Asciio/commit/5a9d9f28b8b6b6ccf402945d21159581e9e1bdab

I have finished writing about the combination of Asciio, figlet and diagon.

**Comment by nkh** [comment]
@qindapao merged in b55d560
