### ISSUE TITLE
Some scrollbar implementation done which will need to be revisited if necessary:

### ISSUE THREAD

**Issue by qindapao** [nkh/P5-App-Asciio#115]
Some scrollbar implementation done which will need to be revisited if necessary:

- changing zoom level doesn't make the widget larger, this means that objects at the bottom and far right may not be displayed; still this is the code that will be used as enlarging the widget to follow the zoom level consumes large amount of memory and cpu and zooming in to a larger extent is very seldom done

- when scrolling the mouse position is not update thus the user needs to click on the scrolled area to insert elements at the right place

_Originally posted by @nkh in https://github.com/nkh/P5-App-Asciio/issues/1#issuecomment-1441853375_

**Comment by qindapao** [comment]
@nkh 

https://github.com/qindapao/P5-App-Asciio/commit/f54568f88df6b76e82169770a81255489b95e8b9

Now room in and out can automatically adjust the size of the canvas.

1. Elements that are on the edge display correctly when zoomed in
2. The number of grids displayed on the canvas remains fixed to reduce memory consumption

**Comment by qindapao** [comment]
@nkh 

If you have the following two values in your personal configuration file, please be sure to update them, otherwise it may not be displayed because the canvas is too large. Now these two values represent the number of grids.

```
CANVAS_WIDTH => 200,
CANVAS_HEIGHT => 150,
```

**Comment by nkh** [comment]
@qindapao merged, good job.
