### ISSUE TITLE
multi connector box

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#122]
current boxes either
- have 4 connectors
- if connection is disabled it is possible to connect anywhere although not to a proper connector thus no optimization is done

a multi connector box has
- 0 connectors
- n connectors
- connector are added, or removed, dynamically
- connector position can be anywhere in the box
- connectors set the minimum box size

Applications:
- routing of many arrows to a box   
- domain specific objects

**Comment by qindapao** [comment]
@nkh This feature is really great.

**Comment by nkh** [comment]
I like Graph::Easy which can do grid based layout.

in the image below I drew the first graph manually, it's optimized and looks better but Graph::Easy takes a simpler description:

```
[ Berlin ] -- train --> [ Bonn ]
[ Bonn ] --> [ Berlin ]
...
```
but it does its routing by adding connectors to boes when needed , long explanation in the link below.

I'd like to be able to create a Graph::Easy like graph automatically and then modify it manually if necessary, that means having a box with dynamic number of connectors.

 ![screenshot_2023-10-03_17-38-35](https://github.com/nkh/P5-App-Asciio/assets/45409/671420c1-96f3-4ddb-a27c-4989f7dc6e03)

http://bloodgate.com/perl/graph/manual/index.html


The multi connector idea can also help with domain specific object #54.

But note that we can already emulate something close for simple drawings by using "enable border connection" or by grouping connectors to objects.

![screenshot_2023-10-03_18-01-25](https://github.com/nkh/P5-App-Asciio/assets/45409/a07303fd-44df-43f4-a4bb-0e341e8e4923)

But there's a slight differences between groups and objects so this needs some serious analysis to write a good solution even if I really like the connector objects I'd like to add them to objects without having to create a group.

**Comment by nkh** [comment]
Another example where having more connectors make sense.

![screenshot_2023-10-04_13-07-45](https://github.com/nkh/P5-App-Asciio/assets/45409/5803d48d-49be-4752-b73b-e9c547b26fec)

**Comment by qindapao** [comment]
@nkh  I opened boarder connection.I didn't realize the importance of this function until I drew this picture.

**Comment by nkh** [comment]
@qindapao it's a nice feature but it has made me lazy because it fixes 95% of my needs I never really worked more on connectors.

Note that the "border connection" doesn't connect to the border but anywhere in a box; maybe I should change the name to something else.

**Comment by qindapao** [comment]
@nkh I know that linking to any part of the box is indeed a very powerful feature.I hope you don't cancel it.Are you planning to cancel this feature?We can optimize the connecter, but I want the border connection to remain.Maybe it would be nice to change the name.Only after reading the documentation and trying it myself did I understand this function.

**Comment by nkh** [comment]
350eaa5

https://github.com/nkh/P5-App-Asciio/blob/main/documentation/mdbook_asciio/src/stencils/box_connectors.md
