### ISSUE TITLE
Solving the problem of automatically increasing the bold font size in GTK3

### ISSUE THREAD

**Issue by qindapao** [nkh/P5-App-Asciio#126]
@qindapao I have idea ... but no plan yet.

I think it's a bit larger work, IE not one day, if you don't need it in 1.9 we can move it to another release, otherwise we keep it in.

In any case I wrote that there was a problem with bold font rendering, the edge of the box is not aligned, you can fix that if you want, it will be used later anyway.

_Originally posted by @nkh in https://github.com/nkh/P5-App-Asciio/issues/110#issuecomment-1638359412_

**Comment by qindapao** [comment]
@nkh 

I solved this problem. Here are the branches to solve the problem.

https://github.com/qindapao/P5-App-Asciio/tree/fix_markup_bold

**Comment by qindapao** [comment]
![image](https://github.com/nkh/P5-App-Asciio/assets/109883544/6ca21c12-b938-4bd8-ac95-bdee8874fa08)

**Comment by qindapao** [comment]
@nkh it is not completely solved. The font size does not necessarily increase by 1.I still need to continue to study the rules.However, you can also merge it first, which can be considered a partial solution. At least it can be aligned in certain font sizes.

**Comment by nkh** [comment]
@qindapao  merged
