### ISSUE TITLE
Arrows should be placed in the root menu

### ISSUE THREAD

**Issue by ceremcem** [nkh/P5-App-Asciio#13]
Currently arrows are here: 

![image](https://github.com/nkh/P5-App-Asciio/assets/6639874/077dcef8-baf9-456b-860a-a892e43e2be3)

However, it would be more convenient to find them in the root: 

![image](https://github.com/nkh/P5-App-Asciio/assets/6639874/269cd510-0ef9-4e14-a864-f40a951c61d5)

**Comment by nkh** [comment]
Everything can be added via a keyboard.

First type «i» then the key corresponding to what you want to add.


 «i» Insert group:

=over 4

 «A»                Add angled arrow

 «a»                Add arrow

 «A-a»              Add unicode arrow

 «B»                Add shrink box

 «b»                Add box

 «A-b»              Add unicode box

 «c»                Add connector

 «E»                Add exec-box no border

 «e»                Add exec-box

 «f»                Insert from file

 «g»                Add group object type 1

 «h»                Add help box

 «i»                Add if-box

 «R»                Add horizontal ruler

 «x»                External command output in a box

 «X»                External command output in a box no frame

 «p»                Add process

 «r»                Add vertical ruler

 «t»                Add text

**Comment by nkh** [comment]
A possibility is to have the main menu as:

![screenshot_2023-06-14_23-46-07](https://github.com/nkh/P5-App-Asciio/assets/45409/f9f47826-c273-4ba4-857a-8d0eb3d30a57)

That's equivalent to what you wanted but all the asciio base objects are in the menu.

**Comment by nkh** [comment]
change made in db5977208096e62aab84b06787a1e11619078ca5

go to your Asciio repo
git pull
perl Build.PL
./build install

**Comment by ceremcem** [comment]
More convenient, thank you!

**Comment by nkh** [comment]
You'll need to pull again, I missed changes for the new menu.

Again, using the keyboard is better, there are commands that are not in the menu at all, for example i + ctl-b let's you insert multiple boxes in one shot, convenient when creating a new diagram.
