### ISSUE TITLE
upload to cpan and test installation

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#138]

**Comment by qindapao** [comment]
When I install asciio in wsl ubuntu today, I found that in addition to the lack of arraw.pm path in build.pl(I see you have fix it.), I also lacked the dependency of hash::slice module.

**Comment by qindapao** [comment]
I installed Hash::Slice manually.

I manually installed some other modules, but I saw that most of the dependencies were added by you.(I didn't use your latest commit when I installed it.)

Or we need some users to test the automatic installation.

**Comment by qindapao** [comment]
@nkh The name of the milestone was changed well. I have the same idea as you.

**Comment by nkh** [comment]
version 19.1.02 tagged and uploaded to cpan.

installation documentation updated, tested in an ubuntu container, both asciio and tasciio running. 

@qindapao
