### ISSUE TITLE
binding completion 

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#141]
works as word completion but for bindings

**Comment by nkh** [comment]
# Prototype

branch help_overlay

![screenshot_2023-11-02_19-56-45](https://github.com/nkh/P5-App-Asciio/assets/45409/9ba16a77-3ca4-409b-9cc2-cbd8dd799dbe)


# Notes

- long lists of sub commands take room and are difficult to read
- top level bindings are not displayed
- top level bindings are many and wouldn't fit the screen
- top level bindings contain mouse bindings which are not accessible via the keyboars

- showing the binding is non optional in the prototype

- showing the bindings should be enable per binding
   - ? show all bindings of the level
   - i? show binding for group i

**Comment by ThomasAstley** [comment]
- Limit number of entries, key to show more, page-system
- Toolbox with most used shortcuts
- FZF search option
- Function keys, Letter + Digit 
-

**Comment by nkh** [comment]
2b0171d

@qindapao I've implemented the popup menu, it's not on by default, documented here https://nkh.github.io/P5-App-Asciio/Bindings.html

it's a good idea to have a quick look here https://github.com/nkh/P5-App-Asciio/blob/main/setup/actions/default_bindings.pl

For you the biggest change is that the cross mode is not 'x' any longer but 'zx'

**Comment by qindapao** [comment]
@nkh I like new bindings and keystrokes.Thank you.

**Comment by qindapao** [comment]
@nkh 

Dynamic prompts are also good.

What do you plan to do next?

stencial pickers?  If it's not too difficult, you can arrange some for me to do.  I'm interested in this at present.

**Comment by nkh** [comment]
@qindapao I wrote #155 and assigned it to you.

I'm happy you want to do it because I don't want to ;) But it's time we have a proper stencil management.

I wrote a few idea, let's discuss them in the ticket.

I continue with 1.9.5, #146 first

**Comment by nkh** [comment]
@qindapao what did you mean with "dynamic prompt"?

**Comment by qindapao** [comment]
@nkh 

Similar to the auto-completion function of the code editor.

**Comment by nkh** [comment]
We'd need a command line for that, #26 exists for it, as you can see the ticket is from 2016, I'd really like to have that but I don't think it's worth it, there are very few commands that are words.

We can discuss your ideas on #26

**Comment by qindapao** [comment]
@nkh You misunderstood me again. I said that your hint is as wonderful as automatic completion.

**Comment by nkh** [comment]
@qindapao Ah  "As" wonderful "As", I thought you wanted to have a command line with completion.

**Comment by nkh** [comment]
@qindapao I'm not a nativ English speaker so we sit in the same wagon.
