### ISSUE TITLE
Support mouse in TUI.

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#142]

**Comment by nkh** [comment]
@qindapao prototype in this branch https://github.com/nkh/P5-App-Asciio/tree/mouse_tasciio

![tasciio_mouse](https://github.com/nkh/P5-App-Asciio/assets/45409/b676fff5-dd23-4dc5-8401-32c926cd0b7a)

**Comment by qindapao** [comment]
@nkh I'll try it tomorrow or the day after tomorrow, it's just amazing. you are great.

**Comment by nkh** [comment]
@qindapao  merged into main b4e0063
