### ISSUE TITLE
keep arrow connection

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#148]
![screenshot_2023-11-06_16-07-44](https://github.com/nkh/P5-App-Asciio/assets/45409/4a93a4e1-42ee-4880-99b7-6981cc46ad00)

**Comment by nkh** [comment]
@qindapao. it makes no sense to disconnect objects moves as a group.

if the user wants to disconnect, she can disconnect the object first then move, or move and then disconnect.

**Comment by qindapao** [comment]
@nkh It seems that the connector enable or disable for the box is only in the right-click menu. I think it can be made into a shortcut key.

I don't want to use the right-click menu anymore since we have the current shortcut keys  haha.

**Comment by qindapao** [comment]
> @qindapao. it makes no sense to disconnect objects moves as a group.
> 
> if the user wants to disconnect, she can disconnect the object first then move, or move and then disconnect.


ok.

**Comment by qindapao** [comment]
@nkh Of course, I'm not saying that right-click menus are not good, they are also part of the software.
