### ISSUE TITLE
Execute script from within Asciio

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#154]
The scripting interface https://nkh.github.io/P5-App-Asciio/for_developers/scripting.html let us generate text renderings and asciio files.

This let's us run the scripts from asciio and insert the elements directly in the current diagram.

possible future functionality
- the scripts displays a UI interface to get parameters from the user
- a command line allows the user to directly input the parameters

![scripting](https://github.com/nkh/P5-App-Asciio/assets/45409/68e82377-294f-4a8c-920c-4964d579be0d)

**Comment by nkh** [comment]
implemented in 4533086

@qindapao

**Comment by qindapao** [comment]
@nkh I noticed this project, and it's a good idea.There are other similar projects. If they find our software, it should save them a lot of energy.
