### ISSUE TITLE
Stencil picker

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#155]
A dialog, possibly modal, where the the user can pick one or more objects

ideas:

- the window in the dialog is asciio
- the contents of the dialog come from an asciio file
- it's possible to select multiple objects
- all selected objects are cloned to the main window
- all selected objects can be copied to the clipboard
- possibility to read contents of the picker from another asciio file
- asciio file is automatically saved
- more than one dialog can be opened and elements can be copied from one to the other
- default stencil files are read only, with the possibility to override

Other ideas in #30 #31 #32

**Comment by qindapao** [comment]
@nkh This is still quite challenging. I need to know more about the software. It doesn't matter. Take my time.

I believe this is meaningful to users.

**Comment by nkh** [comment]
@qindapao it's very meaningful. In a way it's silly to chose stencils by name in a program that is supposed to graphical. the user should be presented a palette of stencils (and be able to modify it).

If you haven't used the clone mode, I recommend giving it a try.

https://nkh.github.io/P5-App-Asciio/editing/cloning.html?highlight=clone#cloning

**Comment by qindapao** [comment]
@nkh 

I implemented a similar function using a very cheap method, and I think it is sufficient. It is to run two software entities by running asciio in the background. Then copy the element via the clipboard. Below is the branch I implemented.

https://github.com/qindapao/P5-App-Asciio/tree/multi_asciio_share_elements

If this is not enough, we will continue to implement a more elegant way later, but I think the function of copying elements between two asciio entities is also useful.

There may be a data size limit on the clipboard. If the data is too large, the copy may fail. There seems to be a limitation on Windows, I haven't tested it on Linux yet.


![multi_asciio_copy_elements](https://github.com/nkh/P5-App-Asciio/assets/109883544/c11fee83-39b3-4992-b03f-c91ef8ee7191)

**Comment by qindapao** [comment]
@nkh I ran two asciio entities via the following in cygwin.

```bash
#!/usr/bin/bash


startxwin >/dev/null 2>&1 &
export DISPLAY=:0.0
sleep 2
asciio "$1" &
```

**Comment by nkh** [comment]
I'm not sure what to think about it but it has the advantage to be simple and it does work.

It's probably simple to implement drag drop.

To make it more "integrated", it should be possible to start the other instance from asciio. I'll have a look at it.

**Comment by nkh** [comment]
@qindapao 

merged and integrated 812480e 

I'll close this issue and open a new one for drag-drop

![asciio_stencil](https://github.com/nkh/P5-App-Asciio/assets/45409/78047644-c64d-45c6-a132-06195ac4e318)

**Comment by qindapao** [comment]
@nkh This is amazing.Users will like it.

**Comment by qindapao** [comment]
@nkh I planted a seed, and you let it sprout and blossom.

**Comment by qindapao** [comment]
@nkh 

In addition, I also think of a usage of base64 coding. I can even record all the templates in my notebook software. Then put each export template and its base64 code together. When I need any template, I copy the base64 code of the corresponding graphic directly in my note software. Then paste it in asciio.


I can put all my things in a txt file. Choose a good name,And put the exported text, so it is convenient to use vim to search.Search for the name, then copy its base64 code and paste it into asciio.

**Comment by nkh** [comment]
@qindapao 

You did most of the work.

It needs a few tweaks:

- drag and drop, I'm looking into it
- it needs to start faster
- some UX work
	- where is the default file located
		- do we have local default files
	- where are the other stencil files located, those who come with Asciio
	- should there be a user defined location for stencils
		do we copy the other stencils there at installation/run
	- if there's a location for the other stencils, should we have a new binding to open stencil in any directory
- more UX work
	- should the window size of the stencil picker be less, for those not using a tiled manager like me?
	- should the size be kept?
- documentation
	- how to add bindings for specific stencils, the command takes a filename

**Comment by qindapao** [comment]
@nkh Ah, indeed, it's not perfect now.  I was just about to ask how to adjust the window ratio.Maybe we have to use GTK3 components.

Other points you mentioned are also worth considering. You can create a new issue and we optimize it later.
