### ISSUE TITLE
Alignment exception after ungrouping

### ISSUE THREAD

**Issue by qindapao** [nkh/P5-App-Asciio#157]
![alignment_exception](https://github.com/nkh/P5-App-Asciio/assets/109883544/8e02c924-5755-4aa6-ae6f-5decca6cfc4b)

Like the phenomenon in the video, if you group and then ungroup. Then the alignment will be abnormal, and the terminal will also print abnormally.

![image](https://github.com/nkh/P5-App-Asciio/assets/109883544/502dd277-11e3-488c-840e-84e36f4c87e7)

**Comment by nkh** [comment]
fixed in 3933063
