### ISSUE TITLE
Remote client interface

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#160]
# IDEAS

An application sends commands to an Asciio instance to generate or modify a graph.

- REST API or via a file descriptor
    - REST API cold be a proxy to the file descriptor
    
# One way communication

Application send command/Asciio scipts, Asciio sends nothing back.

**Comment by nkh** [comment]
implemented in 097f80c 

see documentation at https://nkh.github.io/P5-App-Asciio/for_developers/scripting_execute.html

@qindapao this may be helpful if you want to generate diagrams dynamically from another application, there's a bash example in the documentation above.

**Comment by qindapao** [comment]
@nkh Okay, I'll take the time to look at it.

**Comment by nkh** [comment]
missing Gtk3::Helper in dependencies

**Comment by qindapao** [comment]
@nkh 

I don't fully understand.Can we use this architecture to realize the web front-end in the future?

**Comment by qindapao** [comment]
@nkh I haven't found time to try your remote code yet.It looks interesting and novel.But I still don't have time to use my personal computer until the weekend.

**Comment by nkh** [comment]
@qindapao This is not about the WEB front end, that would have a different architecture.

What this does is offer a canvas, a place where to place and modify elements, that can be accessed remotely.

This can indeed be used to show animations to show how algorithms work.

it is orthogonal to slides, we can use slides AND the web interface for animations, AND of course manually manipulate elements, all at the same time.

**Comment by qindapao** [comment]
@nkh Good, interesting and useful.
