### ISSUE TITLE
Single letter text difficult to move

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#161]
Since it's one character, asciio resized it instead for moving it

**Comment by qindapao** [comment]
@nkh become shrink box we can move.

I have a simple princess, and I wanted to discuss it with you after the zbuffer crossover was fully realized.

But you mentioned it here. I said it by the way.I call it painting mode.Every single-character element is a pixel.We can draw pictures conveniently by using clone mode.The stencial after painting is a lot of boxes with single characters, which is inconvenient to use.Although we can be combined by using strip group.But it will use more space.If these pixels can be combined into a simple box,It may be more convenient to use and save.If the user wants to edit again,We provide a method to split the box into pixel boxes.Then they use the clone mode or various groups to re-create.

It can be easily realized with zbuffer.What do you think of this function?

Of course, turning into a box is not limited to pixels, and can be any element that the user wants to change.And then split into pixels is certain.This operation is dangerous and may destroy the original elements.So users need to know what they are doing.

**Comment by qindapao** [comment]
@nkh Maybe you have a better idea about painting mode.Or you don't like it.

**Comment by qindapao** [comment]
If we see a stencial we like online, we can also edit it again by breaking it into pixels.Without directly editing its text.

**Comment by nkh** [comment]
@qindapao I'm OK with an ASCII art mode. Also the possibility to transform any text into a box content directly in Asciio is a good idea.

We need to have a separate issue for it with a bit more details.

**Comment by nkh** [comment]
Only single character elements created by "create multiple text" have this problem, single characters elements created indivudally have the opposite problem they can be moved but not resized.

**Comment by qindapao** [comment]
@nkh Oh, that's exactly what you said.

**Comment by qindapao** [comment]
@nkh I'll think about the ascii art mode again.

Maybe we need an eraser and an element selection lock sleeve (non-rectangular selection)

I'll reopen an issue when I think about it.

**Comment by nkh** [comment]
Fixed in 504fd11
