### ISSUE TITLE
The shape of the mouse is weird after the clone mode ends

### ISSUE THREAD

**Issue by qindapao** [nkh/P5-App-Asciio#164]
![mouse_error](https://github.com/nkh/P5-App-Asciio/assets/109883544/db574738-6542-4e57-88e1-5f743d84c4f9)

I tested this phenomenon on cygwin and wsl linux.The mouse pointer becomes tilted after the clone mode ends.

**Comment by nkh** [comment]
@qindapao  what branch are you in?

**Comment by qindapao** [comment]
@nkh My computer is off, I can't remember which branch it is in. I'll confirm it tomorrow night.

**Comment by qindapao** [comment]
@nkh I am running on the latest main branch

**Comment by nkh** [comment]
The cursors is hidden in clone mode; it's shown again when exiting clone mode.

I reset the cursor to "arrow" and it looks the same on my box. it seems that "arrow" is not the same as the default arrow in your environment.

I have no idea why right now.

https://github.com/nkh/P5-App-Asciio/blob/a2f3335c0345243d64af630fa496e26094543fcd/lib/App/Asciio/GTK/Asciio.pm#L34-L57

**Comment by qindapao** [comment]
@nkh It's not a big problem, it doesn't affect other functions, it's just visual. Might be a problem with my local settings.Do you need to track it? Just close it if you don't need it.

**Comment by nkh** [comment]
@qindapao Yes we do.

It may work on my machine because I have setup my cursor theme but it should work for everybody.

Here's the list of GTK cursors:

https://docs.gtk.org/gdk3/enum.CursorType.html

as you can see 'arrow' is the cursor you are getting, it may need to be changed to "left_ptr" or "top_left_ptr#, can you please test that?

**Comment by qindapao** [comment]
@nkh I can, but this priority is lowered, I am doing zbuffer integration.

**Comment by qindapao** [comment]
@nkh 

I cached the mouse pointer type, and then used the cached pointer type when restoring. The current test is OK in my environment. Please check if your environment can work normally.

https://github.com/qindapao/P5-App-Asciio/tree/fix_mouse_shape


![fix_cursor](https://github.com/nkh/P5-App-Asciio/assets/109883544/2fdcbb5e-37c7-4dfd-8833-0891d1ede8d2)

**Comment by qindapao** [comment]
@nkh 

https://github.com/qindapao/P5-App-Asciio/tree/fix_mouse_shape

I cached the mouse pointer type, and then used the cached pointer type when restoring. The current test is OK in my environment. Please check if your environment can work normally.

![fix_cursor](https://github.com/nkh/P5-App-Asciio/assets/109883544/e85c701c-48be-4f35-9311-16bb0c7808f0)

**Comment by nkh** [comment]
@qindapao works fine for me, I've merged it here 74b1c1f

Did you try to change "arrow" to "left_ptr"? please try it, without caching, as I can't try in my environment (it works here  because I have a mouse theme I think)

**Comment by qindapao** [comment]
> @qindapao works fine for me, I've merged it here [74b1c1f](https://github.com/nkh/P5-App-Asciio/commit/74b1c1f4db52847e341ee2820635e2c54800f1a4)
> 
> Did you try to change "arrow" to "left_ptr"? please try it, without caching, as I can't try in my environment (it works here because I have a mouse theme I think)


@nkh I did the test as you said and it works fine.

**Comment by qindapao** [comment]
![image](https://github.com/nkh/P5-App-Asciio/assets/109883544/1c3d0e1f-0fec-4d41-91ae-2d5ed5c49da6)

**Comment by nkh** [comment]
@nkh I removed the cached cursor and use 'left_ptr' instead.
