### ISSUE TITLE
Add canvas drag

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#17]
@qindapao can you please write the use case for this functionality?

**Comment by qindapao** [comment]
In fact, it is the drag and drop of the canvas that I mentioned before.Should be simple functionality, I just haven't found the correct way to do it in the GTK3 port, nor can I find examples online.

![drag-drop](https://github.com/nkh/P5-App-Asciio/assets/109883544/ecf61692-a277-4d6d-9079-3d2587a7b562)

**Comment by nkh** [comment]
You can't do that as moving the mouse while clicked would start the selection.

if you're ok with ctl + drag then you can write an action handler for 'C00-motion_notify'. in it you can compare with the mouses previous position and set the scrollbar accordingly, I think it will redraw automatically. it shouldn't be more than a few lines of code

in default_bindings.pl after
```
'Mouse motion'    => ['000-motion_notify',                      \&App::Asciio::Actions::Mouse::mouse_motion    ], 
'Mouse motion 2' = > ['0AS-motion_notify',                      \&App::Asciio::Actions::Mouse::mouse_motion  ], 
```
add
```
'Mouse motion'         => ['C00-motion_notify',                      \&App::Asciio::Actions::Mouse::mouse_drag_canvas   ], 
```

then in Actions::Mouse something like 

```

sub mouse_drag_canvas
{
my ($self, $event) = @_ ;

my ($x, $y) = @{$event->{COORDINATES}}[0, 1] ;

if($event->{STATE} eq 'dragging-button1' && ($self->{PREVIOUS_X} != $x || $self->{PREVIOUS_Y} != $y))
	{
	# SET SCROLLBAR HERE
	return ;
	}

($self->{PREVIOUS_X}, $self->{PREVIOUS_Y}) = ($self->{MOUSE_X}, $self->{MOUSE_Y}) ;
($self->{MOUSE_X}, $self->{MOUSE_Y}) = ($x, $y) ;
}
```

**Comment by qindapao** [comment]
We thought about it together, and I tried to realize it in the same way some time ago, but the screen always flickered, and the movement was not smooth, it should be something wrong. When I have free time, I will try to write it again, and you can help me take a look at that time.

**Comment by qindapao** [comment]
https://github.com/nkh/P5-App-Asciio/commit/91c62937131f91dcf0c549cb47afcef4d7bfbddb

This is the code, currently this code is running problematic, the screen flickers crazily, and the movement is not smooth.

**Comment by qindapao** [comment]
![drug_and_drop_abnormal](https://github.com/nkh/P5-App-Asciio/assets/109883544/2b1d7aab-8e55-4213-b2a7-0593f3ba2151)

**Comment by nkh** [comment]
($self->{MOUSE_X}, $self->{MOUSE_Y}) = ($x, $y) ; should also be set before returning, how does it look then?

**Comment by qindapao** [comment]
> ($self->{MOUSE_X}, $self->{MOUSE_Y}) = ($x, $y) ; should also be set before returning, how does it look then?


There is a small bug in the code, the variables are reversed, and then I added the code to update the mouse position according to your suggestion, and the verification found that it still didn't work. I think there may be the following two reasons.


1. 
When dragging, the values ​​of x and y do not actually change, because the mouse moves with the canvas. Their relative displacement is 0. Some flickering may be that the mouse position is slightly shifted when the drug ends.

2.
The coordinates of x and y are the integer values ​​obtained by dividing the real coordinates by the width and height of the character. The accuracy is greatly lost, so even if it is implemented later, it will not be very smooth.


I still don't know much about gtk3, and I don't know if there is a dedicated interface for dragging.

do you have any good advice?

If it's too troublesome, let's put this question aside for now. But I really like this feature.

**Comment by nkh** [comment]
I've been working on it since 06:00 this morning. I have it working smoothly but I haven't handled all the cases yet. If I get it to work within one or two hours I'll commit in master otherwise in a separate branch so you can try it.

**Comment by nkh** [comment]
partly implemented in master@343cb0f0

**Comment by qindapao** [comment]
Thanks, I'm about to get off work here, I'll try it when I get home.

**Comment by qindapao** [comment]
I tried it and it does work. However, a new problem has been introduced, which affects mouse_duplicate_element 

'Mouse duplicate elements'                    => [['0AS-button-press-1', '000-comma'],      \&App::Asciio::Actions::Mouse::mouse_duplicate_element

**Comment by nkh** [comment]
Good catch! I restored it in master@a5015e0, please test.

**Comment by qindapao** [comment]
https://github.com/nkh/P5-App-Asciio/commit/ce82689eed507ff5be83e15a6f4f6be8f3a62bb5

**Comment by nkh** [comment]
better written as an else block, let me check first

**Comment by nkh** [comment]
What was the problem you fixed exactely?

**Comment by qindapao** [comment]
@nkh 

Maybe my commit massages didn't make it clear. 

Well, if want to drag and drop multiple times, the user will usually press the ctrl key all the time . Then a few times the left mouse button click operation, each click of the mouse is to adjust the position of the interval. There will be no drag and drop at this time, and the coordinates need to be updated. Just try it and you'll see.

**Comment by nkh** [comment]
OK, I suspected that. I have merged the change.

**Comment by qindapao** [comment]
@nkh This function is almost enough. Can this isue be turned off? I think

**Comment by nkh** [comment]
if you look at the commit message https://github.com/qindapao/P5-App-Asciio/commit/e3c23bb3003fadb04bae998ea1cc72ecb3aaf5e0, you'll see that there's more work to do to be complete, even if it is good enough right now.
