### ISSUE TITLE
Accept multiple escape binding fro action groups

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#171]

**Comment by nkh** [comment]
c431260 

@qindapao this fixes binding the same key to enter and escape a group.

I also refactored the whole Actions.pm and integrated the selection mode.

As you can see in the example above we can:
- use multiple bindings to enter a group
- use multiple bindings to escape a group
- use the same binding to enter and escape a group

**Comment by qindapao** [comment]
@nkh 

Ok, I like it very much.
