### ISSUE TITLE
current version of asciio does not load files saved by old version

### ISSUE THREAD

**Issue by HoTschir** [nkh/P5-App-Asciio#182]
I've attached a test file, which is saved by asciio version 1.51.3-1 (Ubuntu 18.04.6 LTS).
[test_old_asciio.zip](https://github.com/nkh/P5-App-Asciio/files/15362587/test_old_asciio.zip)
A freshly installed actual version is not able to load this file. Error messages are:
`user@computer:~$ asciio test_old_asciio.asciio 
GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed at /usr/lib/x86_64-linux-gnu/perl-base/DynaLoader.pm line 218.
GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed at /usr/lib/x86_64-linux-gnu/perl-base/DynaLoader.pm line 218.
GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed at /usr/lib/x86_64-linux-gnu/perl-base/DynaLoader.pm line 218.
GLib-GObject-CRITICAL **: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed at /usr/lib/x86_64-linux-gnu/perl-base/DynaLoader.pm line 218.
Asciio: Warning: can't find setup data '~/.config/Asciio/Asciio.ini'
                               Open`
**`Sereal: Error: Bad Sereal header: Not a valid Sereal document. at offset 1 of input at srl_decoder.c line 619 at /usr/local/share/perl/5.36.0/App/Asciio/Io.pm line 63.`**

Needless to say, the file can be reopened with the old version without any problems.

**Comment by nkh** [comment]
Hi, the newest version is not binary compatible. Do you have drawings you
absolutely need to load in the newest version?


Nadim

**Comment by HoTschir** [comment]
Hi and thank you for your response. 

I've (only) one old drawing. It's not a big one and if neccessary, I can redraw it. 
>> newest version is not binary compatible.
I'm a programmer, too. But don't understand, why a conversion tool is not included, if the data structure has changed.

This is a kick-out criterion for asciio of my "useful-SW-list". I'll redraw it with different tool.

br
Holger
