### ISSUE TITLE
how can i add more stencil?

### ISSUE THREAD

**Issue by simone-viozzi** [nkh/P5-App-Asciio#3]
hi, i never worked with perl so i'm a bit confused about path and other things.

I would to add some more stencil and if possible publish them in this repo, how can i contribute?

**Comment by nkh** [comment]
Hi, sorry for the late reply, I missed your mail.

in the installation directory for asciio, under the directories
setup/stencils there are files you can modify IE:
https://github.com/nkh/P5-App-Asciio/blob/master/setup/stencils/divers

N.

**Comment by nkh** [comment]
You can also add your own file with the same format as the one in the
distribution, To load them you need to add them to
https://github.com/nkh/P5-App-Asciio/blob/master/setup/setup.ini

N.

**Comment by nkh** [comment]
@simone-viozzi , did that fix it for you? I'd like to close the ticket.
