### ISSUE TITLE
Stencils are dynamically managed from asciio

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#30]
User can add and remove stencils to the default stencil list, from asciio

User can add stencils and stencil directories, the later will be represented as a sub entry in the stencil list. It solves nkh/Asciio-2.0#4 

Stencils objects can be assigned shortcut

**Comment by ThomasAstley** [comment]
- Default stencils -> custom stencil
- All stencils window

**Comment by nkh** [comment]
fixed in 3528467 

@qindapao 

this is the latest UX work for the stencils.

I added files "setup/Stencils/computer.asciio, ..." to the distribution, you'll need to copy those .asciio files to your $HOME/.config/Asciio/stencils.

They are not kept in synch with the popup stencils (which may be removed some day).

Binding 'iss' will open a file picker dialog to let you chose a stencil to open, but 'is0', 'is1', 'is2', 'is3', directly open one of those files, see https://nkh.github.io/P5-App-Asciio/editing/drag_drop.html for all bindings.

You can add a stencil in the file picker if you want, the stencils are just normal file so you can add/delete/create groups in them, just remember to save.

Please test and let me know if  the UX is OK.

**Comment by qindapao** [comment]
@nkh I will experience it over the weekend.
