### ISSUE TITLE
Explain: create_code_box

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#37]
@qindapao 

Hi, you've added two bindings that point to  Action::Unsorted::create_code_box

could you please explain what those do?

also note that the bindings don't work

**Comment by qindapao** [comment]
@nkh 

https://github.com/nkh/P5-App-Asciio/commit/efa6f79149366d0bb098c66505cd54dd3a46b233

**Comment by qindapao** [comment]
In addition, the git mode I am talking about is your git mode, just adding connectors and angled arrow type change functions
