### ISSUE TITLE
Enabling Windows Build

### ISSUE THREAD

**Issue by vashnt707** [nkh/P5-App-Asciio#4]
Am a very big fan of Asciio. However despite my several attempts I haven't been able to make it work in windows. I am running a dedicated virtual machine just to have this working in windows. Camelbox is broken & no other alternative such as ActivePerl or StrawberryPerl is working.

Is it feasible to make this work in windows?

**Comment by nkh** [comment]
Hi, I think the simplest is to get camelbox working. You need to download
everything and build it. I tried and failed but other succeeded.

Alternatively you need to get gtk working on Windows. Then it should be
trivial.

Another but maybe not so bad option is to write a new interface not using
gtk.


If you run win10, Wsl, Windows subsystem for lunch, may be even simpler.

Don't give up 😁

I am a Linux user so I can't help much but I will as much as I can.

N

**Comment by vashnt707** [comment]
Thanks for the quick response. I gave these a try. WSL works great. I tried camelbox and finally made it work however the asciio version seems to be 1.1 or so without those curly arrows and other stencils. Let me give a couple of more tries.

**Comment by nkh** [comment]
hi, sorry for the late answer but your mail got lost in the jungle

I am curious how you got camelbox to work.

I can help you upgrade to the latest version if you want.

N

**Comment by vashnt707** [comment]
I had to download each individual packages from google code archive. Then I started a local web server, pointed the root folder during the camelbox setup. As the final installed size became quite large, I ended up using a linux subsystem eventually.

**Comment by nkh** [comment]
would it be possible for you to send me the generated distribution, I'd
like to install camelbox for a few test?
N

**Comment by vashnt707** [comment]
Sorry I don't have the distribution with me now. As mentioned above since it became quite huge, I had to delete it and move on to linux subsystem

**Comment by nkh** [comment]
so you are running asciio in linux subsystem for windows? right?

have you tried using cpan to upgrade asciio?

N

**Comment by vashnt707** [comment]
Linux subsystem has latest version of asciio. Camelbox had an old version which I couldn't update.
