### ISSUE TITLE
Document markup text

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#53]

**Comment by qindapao** [comment]
I found some imprecise places in the markup mode, mainly the ambiguity between regular expressions and arrow elements, Arrows are easily mistaken for marks.which also needs to be corrected.

I'll deal with it when the cross mode is over. Let's do it one by one.

**Comment by nkh** [comment]
Yes, everything in its time.

I have one r two ideas about markdown and object attributes, I think it would be a good idea to be ale to associate some attributes in elements that can be use later by exporters. I'll write them in this ticket for future discussion

from https://github.com/Twinside/asciidiagram

```
 +--------+         +--------+
 | Source +-------->| op1    |
 | {src}  |         \---+----/
 +--------+             |
            +-------*<--/
 +------+<--| op2   |
 | Dest |   +-------+
 |{dst} |
 +------+

::: .src .filled_shape { fill: #AAF; }
::: .dst .filled_shape { stroke: #FAA; stroke-width: 3px; } 
```


![styleExample](https://github.com/nkh/P5-App-Asciio/assets/45409/17f01638-1735-411d-a330-f0d1d32b02db)

**Comment by qindapao** [comment]
@nkh 

https://github.com/qindapao/P5-App-Asciio/commit/7536df86ff8a8fa1e35b308f7736a86c42051015
