### ISSUE TITLE
Interactive overlay example in capture groups

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#66]
@qindapao 

maybe a nice and more interactive way to add multiple objects.

![capture_overlay](https://github.com/nkh/P5-App-Asciio/assets/45409/7fb7533b-aab1-46ee-8b88-9aeb325c7ee4)

**Comment by qindapao** [comment]
That's good. I've thought about it before. How did you achieve it?

**Comment by qindapao** [comment]
I probably understand that the overlay layer provides users with a preview of the currently inserted elements. In GUI, we can use the mouse wheel to switch.

**Comment by qindapao** [comment]
@nkh 

Like exec box, overlay creates infinity.    You are really a master.

**Comment by nkh** [comment]
@qindapao honestly a large part of the credit goes to you, Asciio wouldn't be what it is today without your energy and good ideas.
