### ISSUE TITLE
Arrow attaches through boxes

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#71]
![arrow_attach_through_stack](https://github.com/nkh/P5-App-Asciio/assets/45409/ca8f9a2c-9c32-43ff-9d33-307cc5e3e86d)

**Comment by qindapao** [comment]
@nkh Please send out your chart and I'll see why.

**Comment by nkh** [comment]
@qindapao it's not your code,  it's how Asciio works with our without cross mode. Not sure we should do something about it, how things are organized in three dimensions is best left to the user I think.

**Comment by nkh** [comment]
Left for user to handle, it's simple to move arrow and boxes in the background, this actually help the user see that there's a possibility to connect. transparent mode can also help.
