### ISSUE TITLE
DEMO: hint lines and callback extra functionality, ...

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#73]
@qindapao 

hint lines can be shown, they make aligning much easier

the mouse can be hidden, eg: good when using overlay to show what object will be inserted next

the callback can also access the canvar, in the example a rectangle, following the mouse is drawn

shift-double click on selected arro will change its direction

![demo](https://github.com/nkh/P5-App-Asciio/assets/45409/c445ff36-2578-460c-a0dd-4f340ebceacd)

**Comment by qindapao** [comment]
@nkh 

I was amazed by the recent use of overlay. This alignment prompt is really great, and the new ways to insert elements.It's getting more and more modern.
