### ISSUE TITLE
insert the same type of object again

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#74]
asciio remembers the last inserted element and run command (that is not a mouse movement), bindings (mouse or keyboard) can repeat the last action.

**Comment by qindapao** [comment]
@nkh Like the dot in vim? Sounds awesome

**Comment by nkh** [comment]
I was thinking about a mode where the user selects an object/selected objects and then can clone them.

but you gave me an idea with the dot, something like the git mode a bit

if nothing is selected and dot is pressed, the last inserted element is clone at the mouse position 

if there is a selection, change the overlay to look like the selected objects and clone them when mouse button is pressed


these two modes are slightly different in how they are used, I'll ask my UX specialist about which one to have or if one can have both (it's my daughter who works with UX and design)

**Comment by nkh** [comment]
Lol! it's already implemented. it's called single click mode, to make it work like above needs two changes

- overlay accepts objects, that's for the visual feedback 
- default object to insert again is last object or selection

**Comment by qindapao** [comment]
@nkh 

My daughter is only 6 years old   :)

**Comment by nkh** [comment]
# UX

## last command was modification object

### last command was on group of objects

## last command was insertion of object

same use case as cloning

**Comment by nkh** [comment]
New clone functionality is easy to use and there's little I can think about that would give meaning to the dot functionality.

**Comment by qindapao** [comment]
@nkh 

Ok, we won't do anything extra.
