### ISSUE TITLE
cross close to arrow end

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#75]
![screenshot_2023-07-05_08-40-01](https://github.com/nkh/P5-App-Asciio/assets/45409/2bca614f-da4d-4c78-8d04-3a697840ab7e)
![screenshot_2023-07-05_08-46-17](https://github.com/nkh/P5-App-Asciio/assets/45409/51588750-e9af-4412-b201-2aa8c4f27408)
![screenshot_2023-07-05_08-40-22](https://github.com/nkh/P5-App-Asciio/assets/45409/ffb4c1ef-fc06-4e2c-9fed-01071f48a094)

**Comment by qindapao** [comment]
@nkh 

I deliberately ignored the arrow.I'll just add them back.
