### ISSUE TITLE
Refactoring: delete_cross_elements_cache

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#77]
It's defined in two places and not used at all.
- lib/App/Asciio/Cross.pm:189:5:sub delete_cross_elements_cache
- lib/App/Asciio/Actions/Elements.pm:141:8:$self->delete_cross_elements_cache();
- lib/App/Asciio/Actions/Elements.pm:138:5:sub delete_cross_elements_cache

**Comment by nkh** [comment]
@qindapao this one is for you to check

**Comment by qindapao** [comment]
@nkh 

The code has been completely removed, please check
