### ISSUE TITLE
Refactoring: remove  all cross mode code from stripes::group

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#78]
![screenshot_2023-07-06_09-23-46](https://github.com/nkh/P5-App-Asciio/assets/45409/77888b71-c139-45da-b3b7-0450d7838867)

There's no reason for any of it; specially calling get_overlays!

**Comment by qindapao** [comment]
@nkh 

Please check, it should be fine now. All extraneous code has been removed.
