### ISSUE TITLE
Integrate git_mode_change_arrow_type

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#79]
@qindapao why is it just for git mode?

**Comment by qindapao** [comment]
@nkh Mainly in order to change the angled arrow type globally.Users don't have to change it separately every time.Maybe there is a better way.

**Comment by qindapao** [comment]
@nkh Because in git mode, the angled arrows and connectors generated by users are Cannot be specified at insert time.

I want to add some flexibility.There are separate options for the angled arrow type. This doesn't seem good. There may be a better way to achieve my goal.

**Comment by nkh** [comment]
No it's a good way but I think we can use it in non git mode too.

**Comment by qindapao** [comment]
@nkh   Let users customize their own default types for each element, which can be changed at runtime. So the default shortcut key is for the current default type.

**Comment by qindapao** [comment]
@nkh 

You're right. git mode shouldn't be treated alone.

**Comment by qindapao** [comment]
@nkh 

More and more ideas, shall we set some milestones?

**Comment by nkh** [comment]
I'm adding issues as we go, if you have a clear goal for a milestone just list it and we add it if you want but I'd rather spend time documenting than handling milestones but if you think it's fun there are many issues that are good candidates for milestones.

**Comment by qindapao** [comment]
@nkh 

Documents are more important.There's no need for fancy things.

Let's talk about it if there are more developers in the future.

**Comment by nkh** [comment]
@qindapao I otherwise agree that we should look at the old issues and see which one are related to the UI. I feel that it's a bit difficult to handle things via the popup menu and that we should att least have a simple way to change both arrow heads.

Bindings are nice but we could complete them with some drop down menu.

You wrote: "Let users customize their own default types for each element, which can be changed at runtime. So the default shortcut key is for the current default type", good idea. There are also some related issues about how to handle stencils in the list.
