### ISSUE TITLE
Crossing mode integration error

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#82]
Integration branch:  https://github.com/nkh/P5-App-Asciio/tree/integrate_cross_mode

I have added some debugging output which displays this title "Get crossing mode overlay:" and then the overlay characters. This is the code:

``` perl
my @overlay_elements = App::Asciio::Cross::get_cross_mode_overlays($self) ;

use Data::TreeDumper ;
print DumpTree \@overlay_elements, "Get crossing mode overlays\n" ;

```

and this is the error:
```
*** unhandled exception in callback:
***   Can't use string ("32") as a subroutine ref while "strict refs" in use at /home/nadim/nadim/devel/repositories/perl_modules/P5-App-Asciio/blib/lib/App/Asciio/Cross.pm line 156.
```

**Comment by qindapao** [comment]
@nkh 


use List::Util qw(first) ;
use List::MoreUtils qw(any);

These two sentences should be added to cross.pm

**Comment by nkh** [comment]
You let me know when you have a commit that works, I'm working on a ticket from 2016, lol!

**Comment by qindapao** [comment]
@nkh 

https://github.com/qindapao/P5-App-Asciio/tree/cross_mode_refac

I'm done, please take a look

**Comment by nkh** [comment]
@qindapao is this on top of the branch I shared yesterday?

**Comment by qindapao** [comment]
@nkh 

It was modified based on yours, I did not use the new commit.

**Comment by qindapao** [comment]
@nkh 

I used the following command
 `git commit --amend`

**Comment by nkh** [comment]
@qindapao, works fine, good job.

It's better to not amend commits in an branch where two or more do work, it makes impossible to see the steps. The one merging can squash instead.

What do you think about having the line crossing mode, I think that's a better name, integrated? 

To make it easier to use this mode, it would be nice if you could fix #72, let me know if it is not clear.

**Comment by qindapao** [comment]
@nkh 

Ok, I see, I can use that command in one person's development branch, but it is not suitable for multi-person development branch.

I will modify the name in the next commit.

**Comment by nkh** [comment]
I have merged into master, I recommend you throw away all your branches that are related to this work (I've just done that), and start anew from master for changes
