### ISSUE TITLE
Demo: closing a 7 years old issue!

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#83]
the doc is in 
![screenshot_2023-07-06_22-45-31](https://github.com/nkh/P5-App-Asciio/assets/45409/3898a3f7-9fff-43aa-8bad-bb1a2b9a4480)

check cloning too.

![quick_section](https://github.com/nkh/P5-App-Asciio/assets/45409/2a89648d-42d8-4823-a30d-8a7596d2a30e)

**Comment by qindapao** [comment]
I tried it, very convenient and efficient

**Comment by nkh** [comment]
@qindapao I really dislike using the popup menus, this helps.
