### ISSUE TITLE
cross mode Efficiency optimization

### ISSUE THREAD

**Issue by qindapao** [nkh/P5-App-Asciio#86]
@nkh 

https://github.com/qindapao/P5-App-Asciio/commit/9617794e99891cd12569cd29d3c4ad8a5b6fdb49

For the cross mode, I made some optimizations, only drawing the part that the user can see.

You may think it is unnecessary, but I use cygwin to run asciio, and the efficiency is not as high as that of native linux.

I added the following, because if the canvas is not automatically drawn when the scroll bar is moving, some characters on the cross layer will not be refreshed in time.

$window->signal_connect(configure_event => sub { $self->update_display() if($self->{USE_CROSS_MODE}) ; }) ;
$sc_window->get_hadjustment()->signal_connect(value_changed => sub { $self->update_display() if($self->{USE_CROSS_MODE}) ; }) ;
$sc_window->get_vadjustment()->signal_connect(value_changed => sub { $self->update_display() if($self->{USE_CROSS_MODE}) ; }) ;

**Comment by nkh** [comment]
Do you want this commit integrated already?

**Comment by qindapao** [comment]
@nkh 

If there is no other problem, I hope to merge it.

**Comment by nkh** [comment]
You hope to merge it ... does that mean that I can do the merge now or do I have to wait for your signal?

**Comment by qindapao** [comment]
@nkh 

You can merge now.


I will modify the cross related documents this afternoon.

**Comment by qindapao** [comment]
@nkh 

Sometimes my English expression is not so accurate.

**Comment by nkh** [comment]
You have a fix_strip_group branch #85, is that ready to merge too?

**Comment by qindapao** [comment]
@nkh 

yes
