### ISSUE TITLE
Documentation: Installation in cygwin and wsl

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#89]

**Comment by nkh** [comment]
@qindapao  if you could write something in the beginning of this week I may have a windows person or two willing to give it a try.

**Comment by qindapao** [comment]
@nkh 

It will be a bit troublesome, especially cygwin, I don't want to destroy my environment for the time being, I need to use my other windows computer to do it.

My current computer WSL is not working properly and I am trying to fix it. After the repair is completed, I will start writing WSL related documents first.

**Comment by qindapao** [comment]
@nkh 

But before that, I want to write the documentation of markup mode first. Then modify the document of cross mode.

**Comment by nkh** [comment]
@qindapao it doesn't have to be more advanced than "installation" section found in the link below and it will give us an opportunity to have testers, a friend that comes from the UK this week, after that the opportunity will be gone.

 https://github.com/nkh/P5-App-Asciio/blob/master/documentation/mdbook_asciio/src/guide/installation.md#installation

**Comment by qindapao** [comment]
@nkh 

I'm really sorry, I only have a work computer at the moment, and I don't have another computer with me. If it is WSL, the usage method is no different from that of native Linux.

**Comment by nkh** [comment]
@qindapao it doesn't have to be today :) he'll be here at my place in two days. WSL can wait.

**Comment by qindapao** [comment]
@nkh 

The installation of cygwin is really troublesome, especially the part of installing the perl library. There are a lot of pitfalls, I spent a lot of time, and I am not very confident to copy it on another computer. I will try my best, but I can't guarantee it will be completed. . . .

Because the time of two days is relatively short. . . .

**Comment by qindapao** [comment]
@nkh 

Shouldn't you take your friends to play more often? But you let him test asciio lol

**Comment by nkh** [comment]
@qindapao  write what you can, including a link on how to install cygwin, then I will use that as a test for installation, if it doesn't work I will update the documentation.

I don't own a windows computer at all.

**Comment by nkh** [comment]
Also, where is your user configuration in windows? I guess it's not in /home/user.

**Comment by qindapao** [comment]
@nkh 

give me some time, I will write something about cygwin in the next commit.

**Comment by qindapao** [comment]
@nkh 

E:\programes\cygwin\home\pc\.config\Asciio

**Comment by qindapao** [comment]
@nkh 

https://github.com/qindapao/P5-App-Asciio/commit/7536df86ff8a8fa1e35b308f7736a86c42051015

A brief description of the cygwin operating environment.
There are also documents about markup mode. I don't have time to change the documents related to cross mode today. That basically needs to be rewritten.
