### ISSUE TITLE
Add connecting lines

### ISSUE THREAD

**Issue by nkh** [nkh/P5-App-Asciio#99]
@qindapao 

The line objects are non connecting because they are mainly used to draw tables and such. I'm going to add connecting lines types, I think they are useful for non directed graph and general drawings.

I'll probably re-assign the bindings we have for non connecting lines to them so the bindings will have to change.

**Comment by qindapao** [comment]
@nkh 

No problem, according to your plan.

**Comment by nkh** [comment]
b29afd5


https://github.com/nkh/P5-App-Asciio/blob/b29afd599f2483a951db64b526567b49bd698206/setup/actions/default_bindings.pl#L255-L263

![connecting_lines](https://github.com/nkh/P5-App-Asciio/assets/45409/9312667a-5038-41c4-a6cc-0019308d3c78)
